# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Test display

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
       - name: Build with Ant
         run: ant -noinput -buildfile build.xml

# create a package with the resulting html files.
       - name: Archive HTML
         uses: actions/upload-artifact@v2
         with:
           name: DHARMA_HTMLCollection
           path: texts/edition-translation


#sauvegarder les hmtls
       - run:  |
           git config user.name github-actions
           git config user.email github-actions@github.com
           git add texts/edition-translation
           git commit -m "HTML files are created"
           git push
